### ISSUE TITLE
Big Week

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2018#30]
This week is/has been dedicated to your projects..

What was the status of your project at the beginning of the week compared to the end of the week?
What do you consider your biggest accomplishment this week?
What do you consider your biggest challenge this week?

**Comment by jgardn92** [comment]
The status of my project at the start of the week was completely not started. By the end of the week I had access to my data, I created a directory and structure in my repository to keep my work organized, and I began downloading my data. I also more fully understood the next steps in my project and how to begin doing them.
My biggest accomplishment this week was figuring out how to make Windows(GitBash), Jupyter, and Google Drive all talk to each other in order to get my data.  
My biggest challenge this week was getting my data off of Google Drive.

**Comment by Jeremyfishb** [comment]
**What was the status of your project at the beginning of the week compared to the end of the week?**
This week I didn't know where my actual data was as it had been moved to a different directory, and I also wasn't sure what my next steps were going to be. Now I know where the data is and what steps I can start taking to visualize the data which will guide my analysis.

**What do you consider your biggest accomplishment this week?**
Finding where my data was and getting a better idea of my next steps were the biggest accomplishments this week. 

**What do you consider your biggest challenge this week?**
My biggest challenge this week is to begin to organize my data, including a few preliminary results that are scattered around a few places. The biggest challenge with that will be figuring out where to store the larger data sets and how I will mange them through different platforms.

**Comment by kcribari** [comment]
At the beginning of the week I did not have anything started for this project, other than knowing which data I was going to be working with. By Thursday, I had downloaded the data files, created a directory with various folders (empty for now), and downloaded most/all of the programs I will need to do my analysis. I believe my biggest accomplishment this week is that I am beginning to understand how everything fits together and knowing what the next steps actually are and what they mean for my data. The challenging part, which will continue into next week, is actually executing those steps. I have everything downloaded, but now I have to figure out how to make it all run!

**Comment by wsano16** [comment]
+ *What was the status of your project at the beginning of the week compared to the end of the week?*
At the beginning of the week, I did not have a good idea of what my project would look like because I did not know if I would be able to generate my own data during the quarter. I doubted that I'd have my own 16S data by the end of the quarter, so I was considering doing some WGS just to get practice with new tools. Now I am more certain that I will have 16S data to work with, so I am moving ahead with some of Yue's generously donated data, which I will use to build and test a pipeline for (hopefully) my own data later in the quarter.
+ *What do you consider your biggest accomplishment this week?*
My biggest accomplishment of the week was becoming comfortable using the GitHub desktop app and integrating it into how I work on code. It is so easy to quickly pop off a commit in the desktop app that I don't consider committing to be a burden as I once did. This 
+ *What do you consider your biggest challenge this week?*
I am having trouble getting `fastqc` to run in the command line. I'd rather not use the GUI (for reproducibility's sake), but I am not experienced with adding new programs to my PATH. In the past I've been able to get programs through a networked `pip` install, but now I am forced to actually understand how installations and paths work.

**Comment by yaaminiv** [comment]
At the beginning of the week, I had samples I needed to analyze on Mox, and some analysis parameters I needed to figure out. Now, I'm running the `bismark` pipeline on Mox. I also have validated choices for analysis parameters using data from samples I ran through the same pipeline on a different machine. My biggest challenge was figuring out what parameters would be best for my data analysis pipeline, since it's easier to choose arbitrary parameters than something that makes sense for the study design. My biggest accomplishment this week besides learning how to use a supercomputer was methodically going through my pipeline and understanding why I'm choosing certain parameters to analyze my data.

**Comment by calderatta** [comment]
At the beginning of the week I had nothing except the project objectives. Over the week I acquired exon-capture data to use, went through the methodology from my reference publication, got my project directory organized, filled in documentation in my README.md and Jupyter project, downloaded some of the software required for my project, and figured out how to use FastQC to quality check the sequences. I would consider my biggest accomplishment this week getting my project structure organized. My biggest challenge this week was trying to use Bash for as many tasks as possible. I ran into trouble downloading and using programs like TrimGalore and FastQC, and would like to know how to do more in command line to have my code be more easily reproducible.

**Comment by kimh11** [comment]
What was the status of your project at the beginning of the week compared to the end of the week?
- At the beginning of the week, I did not have an organization structure figured out for my project or where/how to analyze my data. Now, I have a clear idea of what analyses to run, have decided to do this on Mox, and checked that all the programs I want to use are available.

What do you consider your biggest accomplishment this week?
- Learning that I can Rsync to my lab's server to back up/store my large intermediate files. :)

What do you consider your biggest challenge this week?
- My biggest challenge this week was figuring out how to Rsync to my lab's NAS server from Mox to transfer files. To be continued..

**Comment by melodysyue** [comment]
##### What was the status of your project at the beginning of the week compared to the end of the week?
At the beginning of the week, I didn't have a clear directory structure for my project, which was also not linked to the github. Now, I have set up the directory structure and pushed the local files to git. 

##### What do you consider your biggest accomplishment this week?
I set up the bioinformatics pipeline. 

##### What do you consider your biggest challenge this week?
My biggest challenge is to document the scripts. I used bash for most part of my analyses. I will learn jupyter to start documenting my codes.

**Comment by laurahspencer** [comment]
Beginning of last week:  I had links to the RNA Seq data (pooled gonad) for my transcriptome assembly, and some dummy QuantSeq and raw read files to start playing with. I did not have a clue where to begin, though.  

Biggest accomplishment: organizing my thoughts/tasks, and creating a to-do list on my README file. Prior to this week I wasn't exactly sure how I would tackle this project, and while I'm still not clear on all the hurdles, I have a much better picture.   

Biggest challenge: getting started and making any tangible progress, particularly because I've had to "move" between computers twice.

**Comment by hgloiselle** [comment]
At the beginning of the week I did not even have a topic, by the end of the week I had access to some data to use. My biggest accomplishments thus far have been successfully downloading the data and getting FastQC to work. My biggest challenge would be frequently having no idea what’s going on or the future steps to take with my data.

**Comment by grace-ac** [comment]
At the beginning of the week, I had nothing except my basic repository created.

By the end of the week, I created the different directories and readme files. I also got started with the new crab sequence data and ran it through FastQC.

**Comment by magobu** [comment]
What was the status of your project at the beginning of the week compared to the end of the week?
I had no data at the beginning of the week, but after communicating with SMEA group, I got all their raw data and, at least, I was able to start thinking about what tools I needed to get my going.

What do you consider your biggest accomplishment this week?
I met with Ramon Gallego and he explained the workflow for the analysis of their data. I got a much cleared picture of what I'm doing with the data now. I feel that I have gone through the  initial hurdle of "denial" mentality, and I feel that I can take it to completion.

What do you consider your biggest challenge this week?
Dealing with all the information, and dealing with all the issues with my windows laptop. Still if I think about how much I know now than at the beginning of the course I feel pretty accomplished.
