### ISSUE TITLE
Git for Scientists

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2018#38]
This week's reading is on Git. Specifically the reading discusses using Git from the command-line.
What is different in using Git from the command-line (or something you are not experiencing) in comparison with GitHub Desktop?
What are some advantages to using Git at the command-line?

**Comment by yaaminiv** [comment]
1. The use of `git add` to start tracking files and stage them for commits is different from Github Desktop. In the command line, you must specify which files your git repository should track using `git add`. Any changes to tracked files must also be staged with `git add`. Github Desktop does this automatically. If a file is added to your local repository, it's automatically tracked. Any changes to that file are also tracked. It is up to the user to either add large files to `.gitignore`.

2. I've found it's easier to use git at the command-line when I'm making changes to large amounts of files. Sometimes Github Desktop crashes.

**Comment by kcribari** [comment]
For everyday use I would prefer to use the Git Desktop for the visual display of what is being committed and what is ready to push. However, for fixing mistakes, using the command line is much easier. By using git from the command line, I am able to pick and choose what I am committing and which commits I would like to revert or ignore. The git log command also lists all of the commits on file and lists the exact files committed for each one. You are able to select a specific commit in which to work with. Although the Desktop seems to have the same ability, in my experience if was not able to perform the task in the way the command line could. 

The biggest use of the command line for me has been the “git reset HEAD” function. This does not revert commits or pushes, but rather upstages them. When I tried to push a commit that was too large, the commit needed to be upstaged before any other commits could be pushed. The command line was able to do this and free up the desktop version again.

**Comment by Jeremyfishb** [comment]
I'm finding that I like to use Git in the command line as opposed to the desktop. From the command line, it's easier to look in directories and look at the files through simple commands such as ls and cat. IT could just be me, but when I try to do this with GitDesktop, I have to find the commit in the history where I made a change to the directory or file of interest. I also like how it's easy to un-stage a change in the command line that you may not want commited whereas I don't see how to do this from the desktop without having to commit all changes (unless they were ignored).

**Comment by jgardn92** [comment]
Using git from the command line allows you a bit more control over over what you upload as the `git add` command requires you to track files first and then stage them for a commit at each subsequent update. Github Desktop automatically tracks all changes to files in the repository and stages them for a commit.   

It seems like Git from the command can be especially useful for making sure files that are too big for GitHub are properly ignored and won't accidentally get staged for a commit (which has happened to me twice now). I've found with GitHub Desktop that trying to commit a file that is too large will cause it crash and mess with the repository in other ways. By editing the .gitignore file from the command line you can use wildcards and control staging in a more obvious manner than with GitHub Desktop.

**Comment by wsano16** [comment]
The most valuable feature of using the Git CLI is the fine level of control that you have over which files are being tracked. Files are not automatically added to the staging area; `git add` requires that you specify the components of your repository's directory structure that you want to track (and potentially push). On top of that, you can edit your .gitignore file with a command line text editor to specify files within your tracked directories that you want git to ignore. These features are important for making sure that large files, intermediate files, and private files don't get pushed to a repo on GitHub by mistake.

**Comment by kimh11** [comment]
For me, the biggest advantange of command line git is that it's all in the same place. Since I'm already on the command line doing my work, it's easy to type ```git status``` ```git add``` ```git commit``` vs opening up the desktop version and choosing to commit my changes.

The main difference I noticed is the effort required to stage files. Git command line makes your think about what files you're adding and committing while Git Desktop does it all for you.

**Comment by hgloiselle** [comment]
I don't have any experience with using git in the command line yet, but after reading I think I'll try it. The git add function seems particularly useful so that large files won't trip up trying to commit. After having many struggles with GitHub desktop this week and having to manually ignore many files, I look forward to trying git in the command line.

**Comment by magobu** [comment]
### Git from the command-line vs. GitHub Desktop
- I did not know how to use GitHub before this class. It took me some time to get comfortable working with the desktop version. Even if it may seem friendlier and easier to use, now that I read about the GitHub capabilities at the command line, I realize I find it much more versatile. Some advantages of the GitHub at the command-line, are the ability to check your file status with the git status command.
I explored some tutorials for GitHub commands and found[ this one](https://www.youtube.com/watch?v=yXT1ElMEkW8) actually helpful (and the guy is so silly and funny)

**Comment by calderatta** [comment]
So far, my preference is still to use GitHub Desktop because of the user-interface is intuitive to me, but for those more comfortable in Bash, I can see git in command-line being favored for flexibility. The ability to toggle the tracking of certain files in a project or filtering files too large would certainly be beneficial in larger projects (rather than dragging and dropping the files you want to commit).

**Comment by laurahspencer** [comment]
command-line is so quick and easy. I moved to command-line because I ran into some issues with the Desktop version, specifically it froze several times, and I got very confused with the forking situation and ended up copying all my files to a new repo. 

I am, however, interested in moving back to optimize the version history/management functions, which I am not doing currently.  In general I still find it difficult to fix a mistake using the command line (e.g. pushing before pulling, undoing commits seamlessly).

**Comment by melodysyue** [comment]
**Using Git from the command-line** gives you more flexibility, especially with the feature `.gitignore`, where you can specify the files that you don't want to keep track of. It might seems more work to use git on the command line, with all the commands such as `git status`, `git add`, `git commit` and `git reset`. However, by doing this, it forces you to think more carefully what files to commit. 

**GitHub Desktop** has a nice user-friendly interface, good for people who are not comfortable with using command line. But the easy clicks do come with costs. It happens to me a few times that I accidentally commited large files and crashsh my computer:(

**Comment by grace-ac** [comment]
Git command line is good for moving around large files, for easily viewing the contents of directories, and for changing directories. 

Git Desktop has an easy to use interface, however it has crashed for me, as it has for others, due to large file sizes when trying to commit and push. For this I think git command line would be better suited to use.
