### ISSUE TITLE
This week in progress

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2018#46]
For this week “project progress” please describe below what your major accomplishment has been this week.

**NOTE: This is week 5: https://github.com/sr320/course-fish546-2018/wiki#grading**

Thus you have a draft project DUE. 
For this you will need to create a `RELEASE` which is essentially a snapshot of your repo.
an example: https://d.pr/i/38Ygst

What we are looking for in this Draft Product assignment is to have made some progress in analysis beyond having raw data. In addition, there should be some defined plan for completion by week 10.

**Comment by yaaminiv** [comment]
[My release](https://github.com/fish546-2018/yaamini-virginica/releases/tag/v0.1)

Because I'm just waiting on my `bismark` run to finish on Mox, I spent my week ensuring I can easily analyze my files when the alignment finishes. This week my biggest accomplishment was refining a previous Jupyter notebook I had to characterize DML and DMR locations. The script now features a section at the top to set variable path names, which will make reusing the notebook with different files easier.

**Comment by Jeremyfishb** [comment]
My major accomplishment this week was getting my [repo](https://github.com/Jeremyfishb/Jeremy-coral) more organized and plotting some of my data in ordination plots to determine which analyses will be the most interesting. There doesn't appear to be a big difference in proteins between bleached and non-bleached corals but there is a distinct difference between the tissue and the skeletal matrix. So, I will concentrate on tissue and skeletal material and have just figured out how to make eigenvectors (thanks Jennifer and Yaamini!) and will be adding them to some plots to see which proteins are driving the differences. My project release can be found [here](https://github.com/Jeremyfishb/Jeremy-coral/releases).

**Comment by calderatta** [comment]
[Week 5 release](https://github.com/fish546-2018/calder-exon-capture/releases)

My major accomplishment this week was organizing my project and restructuring my [main project markdown file](https://github.com/fish546-2018/calder-exon-capture/blob/master/notebooks/main.ipynb) to be more understandable, and therefore more reproducible. I also made some headway in terms of my project workflow this week, and the main obstacle was understanding some of the source scripts I received for this project and getting them to work with these data. This has lead to me learning additional bash and some perl syntax. By week 10 my goal is to remove contigs that do not match to the markers we targeted (step 9 in my workflow).

**Comment by kcribari** [comment]
[Week 5 Project Release](https://github.com/fish546-2018/Cribari-eDNA/releases/tag/v0.1)

My major accomplishment this week was working through troubleshooting problems with my data. I have completed 8 out of 10 steps for one of sixteen files. However, once all of the steps are completed and the kinks are worked out, it should be fairly easy to do the other 15 files.

**Comment by wsano16** [comment]
[Week 5 Project Release](https://github.com/fish546-2018/will-Chiru16S/releases/tag/v0.1)

My major accomplishments of the week were working around a DADA2 read-pairing error and getting my data through Gneiss. I also was able to make my project Jupyter notebook more coherent and readable. With the bulk of analytical steps done, I look forward to working on translating this work to my own data in the second half of the quarter.

**Comment by jgardn92** [comment]
[Week 5 Project Release](https://github.com/fish546-2018/Jenny-Snailfish/releases/tag/v0.1)
My major accomplishment this week has been installing Stacks on a virtual machine running Ubuntu. This virtual machine runs on my Windows desktop. I was not able to make much progress with my actual data this week due to issues with this install, [detailed here](https://github.com/fish546-2018/Jenny-Snailfish/blob/master/progress/InstallingStacks.md).  
I now have Stacks installed on this virtual machine, as well as access to my Git repository and Jupyter Notebooks. I also have access to resources from other students who routinely use Stacks so analysis should hopefully go a bit smoother from here on out. At least I should no longer have issues with the fact that my machine is Windows.

**Comment by laurahspencer** [comment]
[Week 5 progress - quantseq](https://github.com/fish546-2018/laura-quantseq/releases/tag/v0.1)  

Biggest accomplishments include learning how to access/use Mox and completing a transcriptome assembly using Trinity. I rsynced the transcriptome to ostrich and I am currently using blast to annotate the transriptome with the Uniprot database. Next hurdles include assessing the transcriptome assembly quality, and installing all necessary programs on ostrich (or my own computer) for the quantseq data processing.

**Comment by hgloiselle** [comment]
[Week 5 release](https://github.com/fish546-2018/hope-oyster/releases)

My biggest accomplishment this week has been making some progress using bowtie, including learning how to index a reference genome. My next steps are working to figure out how to get around the error I'm receiving with bowtie so that I can align the two paired end samples and be able to call SNPs.

**Comment by melodysyue** [comment]
[My week 5 release](https://github.com/fish546-2018/Yue-metabarcoding/releases/tag/v1.0)

My biggest accomplishment this week is automate the sequence filtering workflow to process many samples at once. My next step is find unique sequences across all samples and get taxonomy classificiation.

**Comment by kimh11** [comment]
[Week 5 release](https://github.com/fish546-2018/hj-pangolin/releases/tag/v1.0)

My biggest accomplishment this week is 1. learning different ways to move files on and off of Mox and have settled on sftp and wget; 2. running FASTQC using GNU parallel in order to figure out how to run things in parallel and aggregating the results using MultiQC. 

Immediate next goals are getting the reference genome index and running BWA on Mox. I have a base script written but plan on testing it before scheduling it.

My week 10 goals are to finish running BWA, run FreeBayes to call SNPs, and trying a genome-aware primer design software to design primers around SNPs.

**Comment by magobu** [comment]
[W5 release](https://github.com/fish546-2018/marta-eDNA/releases/tag/v0.1)

My biggest accomplishment this week was to be able to run several steps in my eDNA data analysis pipeline using R.

I feel now like I probably will be able to finish the project by week 9! 

Now I would like to get more efficient at using R and Github. and also how to use the markdown feature incorporated in R.

**Comment by grace-ac** [comment]
[Week 5 release](https://github.com/fish546-2018/grace-Cbairdi-transcriptome/releases/tag/v1.0)

Biggest accomplishment was successfully assembling the transcriptome (I figure it is correct because the "Trinity.fasta" file in ```/gscratch/srlab/graceac9/analyses/trinity_out_dir/``` on Mox is large) and learning how to do ```rsync``` (have to remember the ```.``` at the end!!). 

I want to figure out how to use Transrate to check the "goodness" of the transcriptome assembly. 

Now I just need to wrap my head around organizing data, jobs, analyses, outputs, etc. For example, today I worked a lot on thinking about and creating subdirectories on Mox for blastdb, query, analyses, etc. I am also working on doing the same on Hummingbird and have to think about where to keep all the different files.
