### ISSUE TITLE
Setting up Projects

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2018#6]
Based on the reading, what would you consider are the two most important things to consider when setting up a bioinformatics project?

**Comment by magobu** [comment]
The main two points that are emphasized on chapter 2 are the **organization** of all documents in folders (taking care of being consistent with naming files and using simple naming), and the **documentation** (using a text editor like Markdown) of all the steps of the project, including as much details as possible.

**Comment by yaaminiv** [comment]
1. House all files for a project in a single directory, organized by subdirectory if needed. This makes analyzing and keeping track of files easier.
2. Document everything so analysis easily reproduced, including coding environment, software specifications, etc.

**Comment by jgardn92** [comment]
The two most important things when setting up a bioinformatics project are
1. Being organized - make sure all files are in a single directory, further organized with subdirectories, and that files have a consistent, simple yet informative naming scheme.
2. writing everything down - by documenting each step of the process you are ensuring that your results will be reproducible. In order to ensure that they are reproducible make sure to include everything including software versions and the like.

**Comment by wsano16** [comment]
When setting up a bioinformatics project, it is important to consider:

1.  **Organization** - skillful use of directories, subdirectories, and consistent filenames allows for workflow automation. This simplifies and enhances the reproducibility of one's work.

2. **Documentation** - Bioinformatics projects can involve vast amounts of data from a variety of sources, and it is essential to keep track of what data is, where it came from, how it has been processed and with what tools. Documentation ensures that you don't get lost/confused when working with your own data, and allows others reviewing or repeating your work to know exactly what you did. README files are an excellent option for documentation.

**Comment by hgloiselle** [comment]
The two main things to consider when setting up a project are organization and documentation. To organize a project, files should be kept in the same directory and consistently named. It's particularly important to not use spaces in file names. A good organization system means that different collaborators can more efficiently work together; for this reason, it is often better to use relative path names as well. Documentation and keeping track of what is done is both helpful for you and those who wish to reproduce your work. By continuing to document what you do, you are able to figure out where you may have gone wrong or keep track of what you're doing. Others can look at the documentation and understand what you've done.

**Comment by grace-ac** [comment]
I think two of the main considerations for setting up a bioinformatics project are (1) to make sure you have an organization plan that you consistently implement, and (2) that you keep clear, reproducible (by yourself and others) records of what you did and how you did it.

**Comment by Jeremyfishb** [comment]
I agree with what everyone else has already stated, organization and documentation seem to be the best practices for starting up a project so that I, and others, can easily reproduce the project and fix problems with the process.

**Comment by calderatta** [comment]
I also agree that organization and documentation are most important. Organization is important because we are handling large amounts of data (by definition), and we accumulate more files the more we process the data. A good organization system makes locating and managing these files easier and less error-prone. The textbook recommends placing all project files in one project folder, having different directories for different types of files (eg. scripts, raw data, analysis), separating files at different steps. Documentation is important for knowing what data are and where they came from. The text recommends recording all the metadata in a "README" file.

**Comment by zscooper** [comment]
I think it can't be repeated enough but **organization and documentation** seem to be the most important points to remember. Particularly, it is quite important to create an easily navigable file directory that can always be accessed through the same relative paths when scripting. Writing README files for each subfolder also seems like a good step towards recording your organization and making sure to **record commands and program versions** is extremely important for reproducibility.

**Comment by laurahspencer** [comment]
I concur- having a well organized and simple repo is key, and recording everything so that all steps are reproducible. My first repo had a poorly thought-out directory structure (too many subdirectories, names too specific), so I needed to change it later in the game and had to update all the relative paths :/

**Comment by kimh11** [comment]
1. Creating a well-organized directory and file naming structure that is logical to the user. This can include subdirectories for each analysis (e.g. data quality check, alignment, etc) and separate directories for data and scripts. The file naming scheme should allow for easy programming.

2. Documenting. To make the project reproducible, the data, analysis, and workflow should be documented in README files. These should include:
	- workflows and commands (software version and parameters)
	- location, date, version, and method of data download

**Comment by kcribari** [comment]
The most important aspects of creating a project, are keeping a clean and organized file structure and directory, that is readable for both you and others. This makes the project easy to reproduce. 

Documentation is also a key to reproducible results. Proper documentation will mean that you and others will be able to follow the workflow efficiently and easily. You want to document what you did and how you did it, where files are, and also the version of the output.

**Comment by melodysyue** [comment]
Two most important things of setting up a bioinformatics pipeline are 1) name, store and organize all the files in a clear and logical way; 2) give a good overview by readme file. well document each file, comment on each chunk of code to make it fully open and reproducible ;
