### ISSUE TITLE
Git push fails, remote hang up

### ISSUE THREAD

**Issue by laurahspencer** [sr320/course-fish546-2018#92]
I'm trying to do one final push after cleaning up my repo / moving files around, and encounter the "fatal: the remote end hung up unexpectedly" error. It's probably b/c I'm trying to push a very large amount of data at once (a bit over 2GB). No files are individually >100MB.  The internet tells me that I need to increase my Git buffer size [(see this site)](https://confluence.atlassian.com/bitbucketserverkb/git-push-fails-fatal-the-remote-end-hung-up-unexpectedly-779171796.html), but it hasn't worked for me. Any suggestions? 

```
lauras-MacBook-Pro:laura-quantseq laura$ git config --global http.postBuffer 4000000000
lauras-MacBook-Pro:laura-quantseq laura$ git push
Enumerating objects: 1394, done.
Counting objects: 100% (1375/1375), done.
Delta compression using up to 8 threads
Compressing objects: 100% (1352/1352), done.
Writing objects: 100% (1354/1354), 2.23 GiB | 112.99 MiB/s, done.
Total 1354 (delta 1151), reused 2 (delta 0)
error: RPC failed; curl 55 SSL_write() returned SYSCALL, errno = 32
fatal: the remote end hung up unexpectedly
fatal: the remote end hung up unexpectedly
Everything up-to-date
lauras-MacBook-Pro:laura-quantseq laura$ 
```

**Comment by sr320** [comment]
try several smaller commits

**Comment by kubu4** [comment]
That's a lot of data with no files >100MB!

My searching of the internet ([error: RPC failed; curl 55 SSL_write() returned SYSCALL, errno = 32](https://stackoverflow.com/questions/46790394/git-push-fails-with-rpc-failed-curl-55-ssl-write-returned-syscall-errno-10)) suggests the problem is related to overall size of the commit being pushed, as GitHub doesn't technically have a limit on repo size.

Oh, @sr320 beat me to it. See his response above.

**Comment by laurahspencer** [comment]
Good idea, thanks
